algoritmo "Calculando Idade"
var
      Idade, Ano_atual, Ano_Nascimento : Inteiro
inicio
    Ano_atual <- 2021 //
    
    escreval("Quer saber quantas velinhas vão em seu bolo de aniversario")
    escreva("Qual o Ano do Seu Nascimento? ")
    leia(Ano_Nascimento)
    idade<- Ano_Atual - Ano_Nascimento
    escreval("Você Tem ", Idade," Anos" )
    escreval("No Seu Bolo de  anicersario iram ", idade, "Velinha(s)")
fimalgoritmo