Algoritmo "Soma de dois numeros"

Var
   // n1, n2, soma : inteiro

    n1, n2 :real
    media : real


Inicio
      escreval("Somando Dois Numero! ")
      escreva("Escreva um numero: ")
      leia(n1)
      escreval("Escreva outro numero: ")
      leia(n2)
     // soma<- n1 + n2
      //escreva("A Soma entre ", n1, " e ", n2, " é ",soma )
      media<- (n1 + n2)/2
      escreva("A Media entre ",n1," e ",n2," é ", media )
Fimalgoritmo